server:
  port: 8003
#mybatis配置
mybatis:
  type-aliases-package: com.yxy.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud03?useUnicode=true&characterEncoding=utf-8
    username: yxy
    password: yxy108

logging:
  level:
    com.yxy.springcloud.mapper: trace

eureka:
  client:
    service-url:
      defaultZone: http://yxy7001.com:7001/eureka/,http://yxy7002.com:7002/eureka/,http://yxy7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: springcloud-provider-dept8003

info:
  app.name: yxy-springcloud
  company.name: yxy-cloud