server:
  port: 7003

eureka:
  instance:
    hostname: yxy7003.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://yxy7002.com:7002/eureka/,http://yxy7001.com:7001/eureka/